### ISSUE TITLE
I need a good README to this project

### ISSUE THREAD

**Issue by matheusbloise** [matheusbloise/docker-multi-stage-php#1]
The README file must gave some examples with some instruction points.

1 - A logo will be nice!
2 - Prettier template will be nice too...

- Fallow below a simple ideia what you can do in this README file ('is not the rule')

3 - This project has two stage modes, `development` and `production`, you can change this config creating your own docker-compose file. 

4 - Inside this project has a docker-compose.yaml and you can use that if you want.

5 - The `Dockerfile` and docker-compose can be easier edited conform you wanted. The production environment in stage "production" 

6 - You can choose with you want to use sock unix to comunicate with PHP-FPM or TCP connection.

**Comment by enflo** [comment]
I have created a PR to solve this issue. Can you check it? https://github.com/matheusbloise/docker-multi-stage-php-nginx/pull/5

**Comment by matheusbloise** [comment]
Thanks for all, i already linked and assigned the issues to your PR.
