### ISSUE TITLE
ADD License file, open source file

### ISSUE THREAD

**Issue by matheusbloise** [matheusbloise/docker-multi-stage-php#2]
Like all open-source projects, this project need a LICENSE file too, with you want to help this project, you can add on the root project the MIT License file.

**Comment by Ayushchaudhary-Github** [comment]
can you assign this to me. Thanks

**Comment by Ayushchaudhary-Github** [comment]
#4  Done you can close this issue.

**Comment by matheusbloise** [comment]
Hey @YushChaudhary, Thank you for the interest. Just assigned!

Nice Hacktoberfest for you ;)

**Comment by matheusbloise** [comment]
Just one more thing before close this issue, Can you add this license file to the another branch too?

Thanks!

**Comment by Ayushchaudhary-Github** [comment]
well can you specify the branch location.?  Thanks

**Comment by matheusbloise** [comment]
I just replicated your changes to another one too, sorry about that. now everything seems ok.

I will close this issue. Thanks for your contribution, i will glad with you considering the another issues in this project too. thanks!!

**Comment by Ayushchaudhary-Github** [comment]
thanks.
