### ISSUE TITLE
New docker-compose file to set a production example

### ISSUE THREAD

**Issue by matheusbloise** [matheusbloise/docker-multi-stage-php#3]
Would be nice if this project had a docker-compose-cloud.yaml file, but diferent than normal docker-compose file already included in this project, this new file will be a just a example with build stage indicating to production and deployment session ready for docker-swarm.

**Comment by enflo** [comment]
Hi, I have experience working with docker and docker swarm, I can help you with this docker-compose?

**Comment by enflo** [comment]
I have created a PR to solve this issue. Can you check it? https://github.com/matheusbloise/docker-multi-stage-php-nginx/pull/5

**Comment by matheusbloise** [comment]
Hi @enflo, thanks for your interest. i have some points about your PR.

1. The docker-compose file should be named how "docker-compose-cloud.yaml"
2.  Please, keep readme file in English
3. About the production docker-compose, would be nice with you explore more about the deployment tag, about 5 replicas (the number of replicas it's just an example).

I already signed this PR to you, thanks and have a nice rest of weekend.

**Comment by enflo** [comment]
Thank you very much for assigning me and the PR feedback, I will check the points and let you know when I have the changes.

**Comment by enflo** [comment]
@matheusbloise I have added changes as you indicate in the points, I have made an example for development and production of what the deploy configuration would look like. Check it when you can and let me know.

**Comment by matheusbloise** [comment]
hi @enflo, how are you going? Excellent changes, first of all i thought about the changes in normal docker-compose file and especialy the deploy tag in this file. I belive it's gonna be useful with someone wants to use in "testing server / QA" using docker-swarm cluster, and the best about it is no more impacts for who just wants to use local environment

**Comment by matheusbloise** [comment]
I got a little issues on readme file.

1. Update the file name `docker-compose-cloud.yaml` inside the readme file.
2. I miss "about the project" session inside the readme file. You can get some idea at the description session in this project.
3. can you put this logotype on readme file please? follow attached
![logo-docker-php](https://user-images.githubusercontent.com/46876171/135923857-ee22eb05-a18f-47c9-a582-17271c89c488.png)

**Comment by matheusbloise** [comment]
@enflo, i believe after this fixes everything is done, so i gonna close your issues assigned, thanks for help.

#hacktoberfest2021

**Comment by enflo** [comment]
Hi , i'm fine and how are you going? thank you very much for the complimentary comments. I have just made the changes indicated for the readme. 
I hope you found my input helpful and that it may help you in the future.

**Comment by matheusbloise** [comment]
Yeah, sure. I gonna close the issues, You already help me a lot. 

Thanks for your time, have a nice hacktoberfest to you 🇪🇸 🇧🇷
